/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filetools2;

import filetools2.MassRenamingWindow;
import java.io.File;

/**
 *
 * @author Sneha
 */
public class MASS_RENAMING_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form MASS_RENAMING_WINDOW
     */
    public MASS_RENAMING_WINDOW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newname_TextField = new javax.swing.JTextField();
        enterString = new javax.swing.JLabel();
        LABELatTheRate = new javax.swing.JLabel();
        hashLABEL = new javax.swing.JLabel();
        dollarLABEL = new javax.swing.JLabel();
        atrTEXTFIELD = new javax.swing.JTextField();
        hashTEXTFIELD = new javax.swing.JTextField();
        dollarTEXTFIELD = new javax.swing.JTextField();
        atrINC = new javax.swing.JRadioButton();
        atrDEC = new javax.swing.JRadioButton();
        hashINC = new javax.swing.JRadioButton();
        hashDEC = new javax.swing.JRadioButton();
        dollarINC = new javax.swing.JRadioButton();
        dollarDEC = new javax.swing.JRadioButton();
        BUTTONcancel = new javax.swing.JButton();
        BUTTONrename = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterString.setText("      ENTER THE STRING:");

        LABELatTheRate.setText("@");

        hashLABEL.setText("#");

        dollarLABEL.setText("$");

        hashTEXTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashTEXTFIELDActionPerformed(evt);
            }
        });

        dollarTEXTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollarTEXTFIELDActionPerformed(evt);
            }
        });

        atrINC.setText("INC");
        atrINC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrINCActionPerformed(evt);
            }
        });

        atrDEC.setText("DEC");
        atrDEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrDECActionPerformed(evt);
            }
        });

        hashINC.setText("INC");
        hashINC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashINCActionPerformed(evt);
            }
        });

        hashDEC.setText("DEC");
        hashDEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashDECActionPerformed(evt);
            }
        });

        dollarINC.setText("INC");
        dollarINC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollarINCActionPerformed(evt);
            }
        });

        dollarDEC.setText("DEC");
        dollarDEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollarDECActionPerformed(evt);
            }
        });

        BUTTONcancel.setText("CANCEL");
        BUTTONcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONcancelActionPerformed(evt);
            }
        });

        BUTTONrename.setText("RENAME");
        BUTTONrename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONrenameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LABELatTheRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atrTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atrINC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atrDEC)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BUTTONrename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(BUTTONcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hashLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hashTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hashINC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hashDEC)
                                .addGap(27, 27, 27)
                                .addComponent(dollarLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dollarTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollarINC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollarDEC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterString, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTONrename, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTONcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELatTheRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atrTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atrINC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atrDEC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hashINC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hashDEC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollarLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollarTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollarINC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollarDEC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hashTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hashLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hashTEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashTEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hashTEXTFIELDActionPerformed

    private void dollarTEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollarTEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dollarTEXTFIELDActionPerformed

    private void atrINCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrINCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atrINCActionPerformed

    private void atrDECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrDECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atrDECActionPerformed

    private void hashINCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashINCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hashINCActionPerformed

    private void hashDECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashDECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hashDECActionPerformed

    private void dollarINCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollarINCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dollarINCActionPerformed

    private void dollarDECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollarDECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dollarDECActionPerformed

    private void BUTTONrenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONrenameActionPerformed
        
        String rename=newname_TextField.getText();
        String newname=rename;
        
        int a=Integer.parseInt(atrTEXTFIELD.getText());
        int b=Integer.parseInt(hashTEXTFIELD.getText());
        int c=Integer.parseInt(dollarTEXTFIELD.getText());
        
        for (File file : filetools2.MassRenamingWindow.ChosenFiles){
            
            System.out.println(file.getName());
            
            newname=rename;
            
            for (int i=0;i<rename.length();i++){
                
                if (Character.isAlphabetic(rename.charAt(i))){
                    continue;
                }
                
                if (rename.charAt(i)=='@'){
                    System.out.println(a);
                    newname=newname.replaceAll("@", String.valueOf(a));
                    
                    if (atrINC.isSelected()){
                        a=a+1;
                    }
                    if (atrDEC.isSelected()){
                        a=a-1;
                    }
          
          }
                
                if (rename.charAt(i)=='#'){
                    System.out.println(a);
                    newname=newname.replaceAll("#", String.valueOf(b));
                    
                    if (hashINC.isSelected()){
                        b=b+1;
                    }
                    
                    if (hashDEC.isSelected()){
                        b=b-1;
                    }
                    
                }
                
                if (rename.charAt(i)=='$'){
                    
                    newname=newname.replaceAll("$", String.valueOf(c));
                    
                    if (dollarINC.isSelected()){
                        c=c+1;
                    }
                    if (dollarDEC.isSelected()){
                        c=c-1;
                    }
                    
                }
            }
            
            System.out.println(newname);
            File my_file = new File(filetools2.MassRenamingWindow.folderPath + "\\" + file.getName());
            my_file.renameTo(new File(filetools2.MassRenamingWindow.folderPath + "\\" + newname + ".txt"));
            
        }
    }//GEN-LAST:event_BUTTONrenameActionPerformed

    private void BUTTONcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONcancelActionPerformed
        MassRenamingWindow backWindow=new MassRenamingWindow();
        backWindow.setVisible(true);
    }//GEN-LAST:event_BUTTONcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MASS_RENAMING_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MASS_RENAMING_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MASS_RENAMING_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MASS_RENAMING_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MASS_RENAMING_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONcancel;
    private javax.swing.JButton BUTTONrename;
    private javax.swing.JLabel LABELatTheRate;
    private javax.swing.JRadioButton atrDEC;
    private javax.swing.JRadioButton atrINC;
    private javax.swing.JTextField atrTEXTFIELD;
    private javax.swing.JRadioButton dollarDEC;
    private javax.swing.JRadioButton dollarINC;
    private javax.swing.JLabel dollarLABEL;
    private javax.swing.JTextField dollarTEXTFIELD;
    private javax.swing.JLabel enterString;
    private javax.swing.JRadioButton hashDEC;
    private javax.swing.JRadioButton hashINC;
    private javax.swing.JLabel hashLABEL;
    private javax.swing.JTextField hashTEXTFIELD;
    private javax.swing.JTextField newname_TextField;
    // End of variables declaration//GEN-END:variables
}
